### ISSUE TITLE
IE11 my-auto error.

### ISSUE THREAD

**Issue by Curros** [BlackrockDigital/startbootstrap-resume#7]
In the IE11 explorer, the content is not properly centered.

![imagen](https://user-images.githubusercontent.com/600906/35230206-b7e5bc72-ff95-11e7-914a-f35d4c4745fd.png)

**Comment by davidtmiller** [comment]
Not sure about this one, it looks like IE11 isn't playing well with flexbox. This is why on my themes I note that they work in the latest stable release of major browsers. Since IE11 only accounts for 2% of browser usage (and dropping) it's not a priority. If you do come up with a fix for this feel free to open a PR though!
